CLASS zcl_lab_08_work_record_pwc DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

  CLASS-METHODS OPEN_NEW_RECORD
  IMPORTING
  IV_DATE TYPE ZDE_PWC_DATE
  IV_FIRTS_NAME TYPE STRING
  IV_LAST_NAME TYPE STRING
  IV_SURNAME TYPE STRING OPTIONAL.


  PROTECTED SECTION.
  PRIVATE SECTION.
  CLASS-DATA DATE TYPE ZDE_PWC_DATE.
  CLASS-DATA FIRTS_NAME TYPE STRING.
  CLASS-DATA LAST_NAME TYPE STRING.
  CLASS-DATA SURNAME TYPE STRING.



ENDCLASS.



CLASS zcl_lab_08_work_record_pwc IMPLEMENTATION.
  METHOD open_new_record.
  DATE = IV_DATE.
  FIRTS_NAME = IV_FIRTS_NAME.
  LAST_NAME = IV_LAST_NAME.
  SURNAME = IV_SURNAME.
  ENDMETHOD.

ENDCLASS.
