CLASS zcl_lab_09_account_pwc DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  METHODS : SET_IBAN IMPORTING IBAN TYPE STRING,
            GET_IBAN EXPORTING IBAN TYPE STRING.

  PROTECTED SECTION.
  PRIVATE SECTION.
  DATA IBAN TYPE STRING.

ENDCLASS.



CLASS zcl_lab_09_account_pwc IMPLEMENTATION.
  METHOD get_iban.
IBAN = ME->iban.
  ENDMETHOD.

  METHOD set_iban.
ME->iban = IBAN.
  ENDMETHOD.

ENDCLASS.
