CLASS zcl_04_class_pwc DEFINITION
  PUBLIC
*  FINAL -se le quita de la padre para que haya la herencia
  CREATE PUBLIC .

  PUBLIC SECTION.

  METHODS:  SET_COMPANY_CODE IMPORTING IV_COMPANY_CODE TYPE STRING,
            GET_COMPANY_CODE EXPORTING EV_COMPANY_CODE TYPE STRING,

             SET_CURRENCY IMPORTING IV_CURRENCY TYPE STRING,
             GET_CURRENCY EXPORTING EV_CURRENCY TYPE STRING.

 METHODS CONSTRUCTOR IMPORTING IV_QUOTATION TYPE STRING.
DATA QUOTATION TYPE STRING READ-ONLY.
  PROTECTED SECTION.

  DATA: COMPANY_CODE TYPE C LENGTH 4,
        CURRENCY TYPE C LENGTH 3.

  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_04_class_pwc IMPLEMENTATION.
  METHOD get_company_code.

EV_COMPANY_CODE = ME->company_code.

  ENDMETHOD.

  METHOD get_currency.
EV_CURRENCY = ME->currency.


  ENDMETHOD.

  METHOD set_company_code.

ME->company_code = IV_COMPANY_CODE.
  ENDMETHOD.

  METHOD set_currency.
ME->currency = IV_CURRENCY.

  ENDMETHOD.

  METHOD constructor.
 ME->quotation = IV_QUOTATION.
  ENDMETHOD.

ENDCLASS.
