CLASS zcl_01_class_pwc DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS:  CONSTRUCTOR IMPORTING IV_EMPLOYEE_ID TYPE STRING,
    GET_EMPLOYEE RETURNING VALUE(RV_EMPLOYEE_ID) TYPE STRING.
data id type string.
  PROTECTED SECTION.
  PRIVATE SECTION.
    DATA EMPLOYEE_ID TYPE STRING.
ENDCLASS.



CLASS zcl_01_class_pwc IMPLEMENTATION.



METHOD constructor.
       ME->employee_id = IV_EMPLOYEE_ID.
  ENDMETHOD.




  METHOD get_employee.
RV_EMPLOYEE_ID = ME->employee_id.
  ENDMETHOD.

ENDCLASS..
