CLASS zcl_08_class_leon_pwc DEFINITION INHERITING FROM zcl_07_class_animal_pwc
  PUBLIC

  CREATE PUBLIC .

  PUBLIC SECTION.
  METHODS WALK REDEFINITION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_08_class_leon_pwc IMPLEMENTATION.
  METHOD walk.
    RV_WALK = 'EL LEON ANDA'.
  ENDMETHOD.

ENDCLASS.
