CLASS zcl_06_class_pwc DEFINITION INHERITING FROM zcl_05_class_pwc
  PUBLIC

  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_06_class_pwc IMPLEMENTATION.
ENDCLASS.
