CLASS zcl_07_class_animal_pwc DEFINITION
  PUBLIC

  CREATE PUBLIC .

  PUBLIC SECTION.
  METHODS WALK RETURNING VALUE(RV_WALK) TYPE STRING.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_07_class_animal_pwc IMPLEMENTATION.
  METHOD walk.
    RV_WALK ='EL ANIMAL ANDA'.
  ENDMETHOD.

ENDCLASS.
